<svelte:window bind:innerHeight={innerHeight} bind:innerWidth={innerWidth}/>
<div class="main">
    <canvas 
        bind:this={canvas}>
    </canvas>
</div>

<script lang="ts">

    import { onMount } from 'svelte';
	import { dataset_dev, init } from 'svelte/internal';

    let canvas: any;
    let innerHeight: any;
    let innerWidth: any;

    onMount(() => {
        // Canvas //
        const ctx = canvas.getContext('2d');
        canvas.height = innerHeight
        canvas.width = innerWidth

        let particleArray: any[] = []

        // Mouse Handler //
        const mouse = {
            x: 0,
            y: 0,
            radius: 200
        }

        window.addEventListener('mousemove', function(event){
            mouse.x = event.x;
            mouse.y = event.y
            //console.log(mouse.x, mouse.y)
        });

        ctx.fillStyle = "white"
        ctx.font = "30px Cassandra"
        ctx.fillText("Hola que tal", 60 , 70)

        // 100x100px area to copy
        const textCoordinates = ctx.getImageData(0, 0, 300, 100)

        // Particles

        class Particle {
            x: number;
            y: number;
            baseX: number;
            baseY: number;
            size: number = 3; // in pixels
            defaultSize: number = 3;
            density: number = (Math.random()) + 1 // Makes particle faster or slower. Like weight
            constructor(x: number, y: number){
                this.x = x
                this.y = y
                this.baseX = this.x
                this.baseY = this.y
            }

            draw() {
                ctx.beginPath();
                ctx.arc(this.x, this.y, this.size, 0, Math.PI * 2) // Draw a whole circle
                ctx.closePath();
                ctx.fill()
            }

            update() {
                let dx = mouse.x - this.x
                let dy = mouse.y - this.y
                let distance = Math.sqrt(dy * dy + dx * dx)

                let forceDirectionX = dx/distance; // % of distance in x axis
                let forceDirectionY = dy/distance; // % of distance in y axis

                let maxDistance = mouse.radius
                let force = (maxDistance - distance) / maxDistance // The closer to the mouse the stronge the force

                let directionX = forceDirectionX * force * this.density // Amount of force the particle suffers reduced by density
                let directionY = forceDirectionY * force * this.density

                // Movement
                if(distance < maxDistance) { // putting a maxDistance > mouse radius generates magnet effect then push effect around mouse
                    this.x -= directionX
                    this.y -= directionY
                } else { 
                    if (this.x !== this.baseX) {
                        let dx = this.x - this.baseX // Distance to return
                        this.x -= dx/30 // Slowly goes back (in 10 frames of animation)
                    } 
                    if (this.y !== this.baseY) {
                        let dy = this.y - this.baseY
                        this.y -= dy/30
                    }
                }


                /* Change size
                if(distance < 500) {
                    this.size = 50
                } else {
                    this.size = this.defaultSize
                } */


            }
 
        }

        let particleAmount:number = 1000

        function init() {
            particleArray = []
            // Scan pixel data of text generated by canvas (row by row of pixels)
            // Column
            for(let y = 0, y2 = textCoordinates.height; y < y2; y++){
                // Row
                for(let x = 0, x2 = textCoordinates.width; x < x2; x++) {
                    // We grab each pixel from scanned area console.log(textCoordinates)
                    // Each pixel is in rgba (r + g + b + alpha)
                    // 4 positions in array per pixel (1 -> red, 2 -> blue, 3 -> green, 4 -> alpha) 

                    // Opacity > 0.5
                    if (textCoordinates.data[(y * 4 * textCoordinates.width) + (x * 4) + 3] > 128) { 
                        let positionX = x;
                        let positionY = y;
                        particleArray.push(new Particle(positionX * 5, positionY * 5))
                    } 
                }
            }
        }
        init();

        // Animation loop
        function animate() {
            ctx.clearRect(0,0, canvas.width, canvas.height) // Clear canvas each frame
            particleArray.forEach(particle => {
                particle.draw()
                particle.update()
            });
            requestAnimationFrame(animate) // Recursive call to animation loop

        }

        animate();


    })



</script>

<style>
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

.main {
    background: black;
    overflow: hidden;
}


canvas {
    position: absolute;
    top: 0;
    left: 0;
}



</style>